### PR TITLE
breaking change: preserveSymlinks is false by default

### PR DESCRIPTION
**Pull request by zkochan**
This is a follow-up to #131

### CODE REVIEW

**Comment by zkochan** [comment]
OK, what about a pre-major with a next dist-tag?

**Comment by ljharb** [comment]
I'm not clear on what the value would be, when we don't know what other major changes would later be included, and when we don't know when a major release might be (in a week? in a month? in a year?)

In general I'm also not a fan of prereleases; I think if it needs to be released, it should be a real release.

**Comment by zkochan** [comment]
OK, I don't insist.

My issue is that I created some PRs to pass `preserveSymlinks: true` to `resolve`, in packages that don't work with pnpm currently. Some maintainers don't respond though. So I am implementing [a hook-system](https://github.com/pnpm/supi/pull/12) that will be able to override a sub-dependency.

What the hook does is basically overriding `"resolve": "^1.4.0"` with `"resolve": "zkochan/node-resolve"`.

With this changes released as beta, I could rewrite resolve with `"resolve": "^2.0.0-beta.0"` instead.

***
So this is my reason. I am OK to wait, but I think it is unreasonable to wait for a whole year as this is how it should have worked to begin with.

**Comment by ljharb** [comment]
The maintainer would need to respond to include a breaking change anyways :-)

**Comment by zkochan** [comment]
@ljharb now that browserify doesn't preserve symlinks by default (from v16), maybe it is time to release resolve@2 with preserveSymlimks false by default?

**Comment by zkochan** [comment]
Is something blocking the release of resolve v2?

**Comment by zkochan** [comment]
An entire year has passed. Releasing this would mean a lot to pnpm.

**Comment by ljharb** [comment]
I'm confused, why does the default matter to pnpm? All the current libs using qs v1 might not upgrade, or might upgrade while setting the option explicitly to `true`.

**Comment by zkochan** [comment]
But there will be still a big chunk that will update and will not change `preserveSymlinks`. Which would be a big improvement already.

**Pull request merged**
