### PR TITLE
correctly resolve paths that are on networked drives

### PR DESCRIPTION
**Pull request by GeekMode**
This is to fix issue #155 where paths don't resolve when it refers to a networked location. The leading backslash gets stripped off which turns paths such as '\\\\ip\\dir' into '\\ip\dir'.

### CODE REVIEW

**Comment by ljharb** [comment]
@GeekMode ping, any interest in completing this PR?

**Comment by TimvdEijnden** [comment]
@ljharb I just found out about this issue because causes circular dependencies are being resolved correctly on Windows by using https://github.com/pahen/madge/ it uses https://github.com/dependents/node-filing-cabinet/ which uses this resolve package. While it does work on macOs.

After investigating for 2 days I've found that #155 is the same issue by debugging the code. After making the same modification the circular dependencies are found. If the author is not continuing with this PR I want to create a new one with tests. This is what came out of my investigation:

Windows with fix from this PR:
```
dirs = 
0:"C:\Users\tim\myProject\src\node_modules"
1:"C:\Users\tim\myProject\src"
2:"C:\Users\tim\myProject\node_modules"
3:"C:\Users\tim\myProject\src"
4:"C:\Users\tim\node_modules"
5:"C:\Users\tim\myProject\src"
6:"C:\Users\node_modules"
7:"C:\Users\tim\myProject\src"
8:"C:\node_modules"
9:"C:\Users\tim\myProject\src"
```

Windows with bug:
```
dirs = 
0:"C:\Users\tim\myProject\src\node_modules"
1:"C:\Users\tim\myProject\src\C:\Users\tim\myProject\src"     <------------------ wrong, does not exist
2:"C:\Users\tim\myProject\node_modules"
3:"C:\Users\tim\myProject\C:\Users\tim\myProject\src"         <------------------ wrong, does not exist
4:"C:\Users\tim\node_modules"
5:"C:\Users\tim\C:\Users\tim\myProject\src"                  <------------------ wrong, does not exist
6:"C:\Users\node_modules"
7:"C:\Users\C:\Users\tim\myProject\src"                      <------------------ wrong, does not exist
8:"C:\node_modules"
9:"C:\C:\Users\tim\myProject\src"                            <------------------ wrong, does not exist

paths =
0:"C:\Users\tim\myProject\src"
1:"C:\Users\tim\myProject"
2:"C:\Users\tim"
3:"C:\Users"
4:"C:\"

modules = 
0:"node_modules"
1:"C:\Users\tim\myProject\src"
```

--- 

macOS with fix from this PR:
```
dirs = 
0:"/Users/tim/git/myProject/src/node_modules"
1:"/Users/tim/git/myProject/src"
2:"/Users/tim/git/myProject/node_modules"
3:"/Users/tim/git/myProject/src"
4:"/Users/tim/git/node_modules"
5:"/Users/tim/git/myProject/src"
6:"/Users/tim/node_modules"
7:"/Users/tim/git/myProject/src"
8:"/Users/node_modules"
9:"/Users/tim/git/myProject/src"
10:"/node_modules"
11:"/Users/tim/git/myProject/src"
```

macOS with bug:
```
dirs = 
0:"/Users/tim/git/myProject/src/node_modules"
1:"/Users/tim/git/myProject/src/Users/tim/git/myProject/src"  <------------------ wrong, does not exist
2:"/Users/tim/git/myProject/node_modules"
3:"/Users/tim/git/myProject/Users/tim/git/myProject/src"      <------------------ wrong, does not exist
4:"/Users/tim/git/node_modules"
5:"/Users/tim/git/Users/tim/git/myProject/src"               <------------------ wrong, does not exist
6:"/Users/tim/node_modules"
7:"/Users/tim/Users/tim/git/myProject/src"                   <------------------ wrong, does not exist
8:"/Users/node_modules"
9:"/Users/Users/tim/git/myProject/src"                       <------------------ wrong, does not exist
10:"/node_modules"
11:"/Users/tim/git/myProject/src"        

paths = 
0:"/Users/tim/git/myProject/src"
1:"/Users/tim/git/myProject"
2:"/Users/tim/git"
3:"/Users/tim"
4:"/Users"
5:"/"

modules = 
0:"node_modules"
1:"/Users/tim/git/myProject/src"
```

Only thing that remains would be filtering out the duplicates.

**Comment by ljharb** [comment]
@TimvdEijnden thanks for confirming! please don't make another PR, but if you provide a link to the tests (on your own fork), I'll pull them into the PR so we can bring it in!

**Comment by TimvdEijnden** [comment]
@ljharb Yes I'll provide them today.

**Comment by TimvdEijnden** [comment]
@ljharb Here they are https://github.com/TimvdEijnden/resolve/commit/2e4499ba8b0dcd957129a732b40284ae3fada2a1

Once this is merged and published to NPM, I'll update the following projects to update the dependencies:
- https://github.com/dependents/node-filing-cabinet/ should update the resolve dependency
- https://github.com/dependents/node-dependency-tree should update the filing-cabinet dependency
- https://github.com/pahen/madge/ should update the dependency-tree dependency

Then I can finally update the madge depedency in our project 😬

**Comment by ljharb** [comment]
If all of those are properly using `^`, you won't need to make any of the intervening PRs.

**Comment by TimvdEijnden** [comment]
Yes will check that first once resolve has a new release

**Comment by TimvdEijnden** [comment]
@ljharb Do you know when a new release is planned?

**Comment by ljharb** [comment]
No plans, just as soon as i have time to do it.

**Comment by ljharb** [comment]
v1.11.1 is released.

**Pull request merged**
