### PR TITLE
Fix symlink resolve

### PR DESCRIPTION
**Pull request by Diokuz**
The problem: `preserveSymlinks = false ` does not work in sync mode.

### CODE REVIEW

**Comment by Diokuz** [comment]
I made it, but for unknown reasons, it fails on runner. Locally everything is okay.

**Comment by Diokuz** [comment]
Original problem is https://github.com/dependents/node-filing-cabinet/issues/81

**Comment by ljharb** [comment]
The new test still fails for me locally, on my Mac.

**Comment by ljharb** [comment]
I've added this to #197.

**Pull request merged**
