### PR TITLE
Do not throw on missing files in isFile/Dir

### LINKED ISSUE #255: Use throwIfNoEntry for default isFile and isDirectory
Similar to https://github.com/webpack/enhanced-resolve/issues/316

Performance of skipping error generation is significant (mini-benchmark present in above issue) and the API is backward compatible. 

Since this project doesnt use graceful-fs, this change should be available to make right now. I do somewhat worry about usage of monkeypatched graceful-fs, though, as that seems to fall into a weird grey area of deciding semver.

### PR DESCRIPTION
**Pull request by markjm**
Resolves #255

### CODE REVIEW

**Comment by markjm** [comment]
Just a warning: it seems appveyor is not testing latest versions of node where this should actually cause a functionality change. I have ran the tests locally, and change is very simple based on node docs - but the PR checks are not covering that case

**Comment by ljharb** [comment]
Appveyor tests on node 14, 15, and 16, all of which should have this option.

**Comment by markjm** [comment]
> Appveyor tests on node 14, 15, and 16, all of which should have this option.

Ah, ok. I was just seeing this link, but I see the other versions on Github Checks view
https://ci.appveyor.com/project/ljharb/resolve/builds/41366169

**Comment by ljharb** [comment]
oh lol you're right; i have the new versions locally but they fail for unrelated reasons.

**Review by ljharb — APPROVED** [review]
Seems fine; if tests pass on v2, I'll also try it on the v1 branch, and will land both if tests pass on both.

**Pull request merged**
